CXXFLAGS += -static -O1 -g -std=c++11
LIBSRC = BitBuffer QrCode QrSegment compressImage sha1 layouts Adafruit_GFX
objects = image.o pbmToCompressed.o compressImage.o BitBuffer.o QrCode.o QrSegment.o sha1.o layouts.o Adafruit_GFX.o
VPATH = qr_code_generator:web:Adafruit-GFX-Library
CXX=g++
CC=gcc
CFLAGS += -static
SHELL := /bin/bash

#This makefile has recursive test and deploy functions.
#This is to make up for the limitations of make, which can't source bash scripts
$(info MAKELEVEL=$(MAKELEVEL))
ifeq ($(MAKELEVEL), 0)
test:
	bash -c "source ./web/config/settings.cfg; \
		for var in \$$(compgen -v); do export \$$var; done; \
		$(MAKE) $@"
else
test: genimg pbmToCompressed genconfig 
	source ./web/config/settings.cfg
	rm -rf $(buildTimeWebDirectory)/test/
	mkdir $(buildTimeWebDirectory)/test
	mkdir $(buildTimeWebDirectory)/test/log
	mkdir $(buildTimeWebDirectory)/test/image_data
	mkdir $(buildTimeWebDirectory)/test/voltage_monitor
	mkdir $(buildTimeWebDirectory)/test/voltage_monitor/data
	cp -r web/config $(buildTimeWebDirectory)/test/config
	cp -r web/plugins $(buildTimeWebDirectory)/test/plugins
	cp -r web/plugin_dependencies $(buildTimeWebDirectory)/test/plugin_dependencies
	cp -r web/device_manager $(buildTimeWebDirectory)/test/device_manager
	cp web/.htaccess $(buildTimeWebDirectory)/test/
	cp web/index.html $(buildTimeWebDirectory)/test/
	cp web/genimg $(buildTimeWebDirectory)/test/
	cp web/pbmToCompressed $(buildTimeWebDirectory)/test/
	cp web/get_image.php $(buildTimeWebDirectory)/test/
	cp web/get_image.sh $(buildTimeWebDirectory)/test/
	cp web/booked.sh $(buildTimeWebDirectory)/test/
	cp web/get_png.php $(buildTimeWebDirectory)/test/
	cp web/rawToPng.sh $(buildTimeWebDirectory)/test/
	cp web/unix_time.php $(buildTimeWebDirectory)/test/
	cp web/r.php $(buildTimeWebDirectory)/test/
	chmod -R -f g+rw $(buildTimeWebDirectory)/test
endif

ifeq ($(MAKELEVEL), 0)
deploy:
	bash -c "source ./web/config/settings.cfg; \
		for var in \$$(compgen -v); do export \$$var; done; \
		$(MAKE) $@"
else
deploy: genimg pbmToCompressed genconfig 
	source ./web/config/settings.cfg
	rm -rf $(buildTimeWebDirectory)/config
	rm -rf $(buildTimeWebDirectory)/device_manager
	rm -rf $(buildTimeWebDirectory)/image_data
	rm -rf $(buildTimeWebDirectory)/plugins
	rm -rf $(buildTimeWebDirectory)/plugin_dependencies
	mkdir -p $(buildTimeWebDirectory)/log
	mkdir $(buildTimeWebDirectory)/image_data
	mkdir -p $(buildTimeWebDirectory)/voltage_monitor/data
	cp -r web/config $(buildTimeWebDirectory)/config
	cp -r web/plugins $(buildTimeWebDirectory)/plugins
	cp -r web/plugin_dependencies $(buildTimeWebDirectory)/plugin_dependencies
	cp -r web/device_manager $(buildTimeWebDirectory)/device_manager
	cp web/.htaccess $(buildTimeWebDirectory)/
	cp web/index.html $(buildTimeWebDirectory)/
	cp web/genimg $(buildTimeWebDirectory)/
	cp web/pbmToCompressed $(buildTimeWebDirectory)/
	cp web/get_image.php $(buildTimeWebDirectory)/
	cp web/get_image.sh $(buildTimeWebDirectory)/
	cp web/booked.sh $(buildTimeWebDirectory)/
	cp web/get_png.php $(buildTimeWebDirectory)/
	cp web/rawToPng.sh $(buildTimeWebDirectory)/
	cp web/unix_time.php $(buildTimeWebDirectory)/
	cp web/r.php $(buildTimeWebDirectory)/
	chmod -R -f g+rw $(buildTimeWebDirectory)
endif

gcal : 
	go build -o web/plugin_dependencies/google/gcal web/plugin_dependencies/google/gcal.go 

genconfig :
	echo "#!/bin/bash" > web/config/database.sh
	echo "#Do not edit this file! It is autogenerated by the makefile, and will be overwritten!" >> web/config/database.sh
	echo "#Instead, edit settings.cfg" >> web/config/database.sh
	cat web/config/settings.cfg >> web/config/database.sh
	cp web/config/settings.cfg web/config/temp
	sed -i 's/^\(.*\)$$/\$$config->\1;/' web/config/temp
	echo "<?php" > web/config/dbconfig.php
	echo "#Do not edit this file! It is autogenerated by the makefile, and will be overwritten!" >> web/config/dbconfig.php
	echo "#Instead, edit settings.cfg" >> web/config/dbconfig.php
	echo '$$config = new StdClass();' >> web/config/dbconfig.php
	cat web/config/temp >> web/config/dbconfig.php
	echo "?>" >> web/config/dbconfig.php
	rm web/config/temp

genimg : image.o compressImage.o BitBuffer.o QrCode.o QrSegment.o layouts.o Adafruit_GFX.o
	$(CXX) image.o $(LIBSRC:=.o) $(CXXFLAGS) -o web/genimg

pbmToCompressed : pbmToCompressed.o compressImage.o
	$(CXX) pbmToCompressed.o compressImage.o sha1.o $(CXXFLAGS) -o web/pbmToCompressed

image.o : image.h
pbmToCompressed.o : pbmToCompressed.cpp compressImage.cpp compressImage.h
compressImage.o : compressImage.h sha1.o key.h
BitBuffer.o : BitBuffer.hpp
QrCode.o : QrCode.hpp
QrSegment.o : QrSegment.hpp
sha1.o : sha1.h
layouts.o : layouts.h
Adafruit_GFX.o : Adafruit_GFX.h

debug:
	$(CXX) image.cpp $(LIBSRC:=.cpp) $(CXXFLAGS) -g -o web/genimg
	$(CXX) pbmToCompressed.cpp compressImage.cpp $(CXXFLAGS) -g -o web/pbmToCompressed

clean : 
	rm $(objects)
