#!/bin/sh

# $1 is the filepath
# $2 is the width of the image
# $3 is the height of the image

png="$1.png"
pbm="$1.pbm"
echo "P4" > $pbm
echo "#Image generated by script" >> $pbm
echo "$2 $3" >> $pbm;
cat $1 >> $pbm
convert $pbm $png
