#!/bin/sh

png="$1.png"
pbm="$1.pbm"
echo "P4" > $pbm
echo "#Image generated by script" >> $pbm

#The resolution of each layout is contained here
head -n $(($2 + 1)) <<EOF | tail -n 1 >> $pbm
384 640
400 300
640 384
640 384
400 300
400 300
400 300
640 384
400 300
400 300
640 384
EOF

cat $1 >> $pbm
convert $pbm $png
